apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config-map
data:
  file1.txt: |-
    test to see if you remember yaml 
    what will be the outcome of this text?
  data.csv: |
    color, code
    grey, 1
    black, 2
    white, 3
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: another-cm
data:
  my.variable: 'test-env'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
data:
  SPECIAL_LEVEL: very
  SPECIAL_TYPE: charm
---
apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: busybox
      command: [ "/bin/sh", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      env:
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              name: another-cm
              key: my.variable
      envFrom:
      - configMapRef:
          name: special-config
      volumeMounts:
      - name: config-volume
        mountPath: /opt/config
  volumes:
    - name: config-volume
      configMap:
        name: my-config-map
