apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-local-storage
  labels:
    owner: dont-steal-my-storage
spec:
  capacity:
    storage: 20Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  local:
    path: /srv/my-local-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - k02
