apiVersion: v1
kind: Pod
metadata:
  name: my-third-pod
  labels:
    app: third-pod
spec:
  containers:
    - image: gcr.io/kuar-demo/kuard-amd64:blue
      name: kuard
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      resources:
        requests:
          cpu: "500m"
          memory: "128Mi"
        limits:
          cpu: "1000m"
          memory: "256Mi"
      livenessProbe:
        httpGet:
          path: /healthy
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /ready
          port: 8080
        initialDelaySeconds: 30
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: my-third-pod-lb-svc
spec:
  type: LoadBalancer
  selector:
    app: third-pod
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
